export const REQUEST_STATES = {
  IDLE: "IDLE",
  PENDING: "PENDING",
  FULFILLED: "FULFILLED",
  REJECTED: "REJECTED",
};

export const APPOINTMENT_STATUSES = {
  SCHEDULED: "SCHEDULED",
  FINISHED: "FINISHED",
  CANCELED: "CANCELED",
};
